accounts/urls.py
from django.urls import path
from .views import (
    get_profile_comments,
    index,
    portfolio,
    settings,
    contactme_complete,
    ContactmeView,
    RegistrationView,
    LoginView,
    LogoutView,
    VerificationView,
    PasswordChangeView,
    PasswordChangeDoneView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
    UsernameChangeView,
    delete_account,
    get_profile,
    ProfileChangeView,
)

app_name = 'accounts'

urlpatterns = [
    path('', index, name='home'),
    path('portfolio', portfolio, name='portfolio'),
    path('settings', settings, name='settings'),
    path('contactme', ContactmeView.as_view(), name='contactme'),
    path('contactme/complete', contactme_complete, name='contactme_complete'),
    path('registration/', RegistrationView.as_view(),
         name='registration'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('activate/<uidb64>/<token>/',
         VerificationView.as_view(), name='activate'),
    # change password
    path('password-change/', PasswordChangeView.as_view(), name='password_change'),
    path('password-change/done', PasswordChangeDoneView.as_view(),
         name='password_change_done'),
    # reset password
    path('password_reset/', PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('password_reset/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/complete/', PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
    path('username_change', UsernameChangeView.as_view(), name='username_change'),
    path('acccount_delete/<uuid:user_id>',
         delete_account, name='acccount_delete'),
    # profile
    path('profile', get_profile, name='profile'),
    path('profile-comments', get_profile_comments, name='profile_comments'),
    path('profile-change', ProfileChangeView.as_view(), name='profile_change')
]

articles/urls.py
from django.urls import path
from .views import (
    article_list,
    article_search,
    article_detail,
    like_unlike_article,
    article_tag,
    article_category,
    create_comment,
    delete_comment
)

app_name = 'articles'

urlpatterns = [
    path('', article_list, name='article-list'),
    path('search', article_search, name='article-search'),
    path('detail/<uuid:pk>', article_detail, name='article-detail'),
    path('detail/like/<uuid:pk>', like_unlike_article, name='like'),
    path('category/<str:category>', article_category, name='article-category'),
    path('tag/<str:tag>', article_tag, name='article-tag'),
    path('comment/<uuid:article_id>', create_comment, name='comment-create'),
    path('comment-delete/<uuid:comment_id>',
         delete_comment, name='comment-delete'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls', namespace='accounts')),
    path('articles/', include('articles.urls', namespace='articles')),
    re_path('markdownx/', include('markdownx.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.contrib.auth import get_user_model
from django.conf import settings
from django.utils import timezone
# from rest_framework_simplejwt.tokens import RefreshToken
import uuid
import os


class UserManager(BaseUserManager):

    def create_user(self, username, email, password=None):
        """
        Create and save a user with the given username, email, and password.
        """
        if not username:
            raise ValueError('The given username must be set')
        if not email:
            raise ValueError('The given email must be set')

        # email addressの正規化
        email = self.normalize_email(email)
        # username
        username = self.model.normalize_username(username)
        user = self.model(username=username, email=email)
        # passwordをハッシュ化してから設定
        user.set_password(password)
        # self._dbは、settings.pyで設定したdefaultのデータベース
        user.save(using=self._db)
        return user

    def create_superuser(self, username, email, password):
        user = self.create_user(username, email, password)
        user.is_superuser = True
        user.is_staff = True
        user.is_verified = True

        user.save(using=self._db)
        return user


class User(AbstractBaseUser, PermissionsMixin):
    username_validator = UnicodeUsernameValidator()

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    email = models.EmailField(max_length=50, unique=True)
    username = models.CharField(max_length=150, validators=[
                                username_validator], unique=True)
    # ユーザー登録の確認メールのURLが押されると、is_verifiedがTrueになる。
    is_verified = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    date_joined = models.DateTimeField(default=timezone.now)

    objects = UserManager()
    # 登録時にユーザー名の代わりにメールアドレスを利用する
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def __str__(self):
        return self.email


def upload_avatar_path(instance, filename):
    profile_avarar_path = 'avatars/avatar_{0}.jpg'.format(str(instance.id))
    full_path = os.path.join(settings.MEDIA_ROOT, profile_avarar_path)
    # '/'.join(['avatars', str(instance.id) + str(".") + str(ext)])
    # ext = filename.split('.')[-1]
    if os.path.exists(full_path):
        os.remove(full_path)
        # return profile_avarar_name_0
    # else:
    return profile_avarar_path
    # return '/'.join(['avatars', str(instance.id) + str(".") + str(ext)])


class Profile(models.Model):
    id = models.UUIDField(default=uuid.uuid4, primary_key=True, editable=False)
    nick_name = models.CharField(max_length=20)
    user = models.OneToOneField(
        get_user_model(), related_name='profile', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    img = models.ImageField(blank=True, null=True,
                            upload_to=upload_avatar_path)
    # followers = models.ManyToManyField(
    #     get_user_model(), related_name="following", blank=True)
    # bio = models.TextField(default="", blank=True, null=True)

    def __str__(self):
        return self.nick_name

accounts/forms.py
from django.contrib.auth.forms import PasswordResetForm, SetPasswordForm

class MyPasswordResetForm(PasswordResetForm):
    """パスワード忘れたときのフォーム"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


class MySetPasswordForm(SetPasswordForm):
    """パスワード再設定用フォーム(パスワード忘れて再設定)"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

accounts/views.py
from unicodedata import category
from django.http import HttpResponse, JsonResponse
from urllib.request import HTTPRedirectHandler
from django.contrib import messages
from django.contrib.auth import authenticate, get_user_model, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import (
    PasswordChangeView, PasswordChangeDoneView, PasswordResetView,
    PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
)
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import EmailMessage
from django.shortcuts import render, redirect
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.urls import reverse
from django.urls.base import reverse_lazy
from django.views import View
from django.core.mail import send_mail, BadHeaderError
from articles.models import Category, Post
from django.conf import settings as conf_settings
from django.contrib.auth.decorators import login_required

from .forms import (
    MyPasswordResetForm, MySetPasswordForm
)
from .models import Profile
from .utils import EmailUtil, account_activation_token


def index(request):
    # posts = Post.objects.all()
    categories = Category.objects.all()
    for_range = [i for i in range(10)]

    context = {
        "categories": categories,
        "for_range": for_range,
    }
    return render(request, 'home.html', context)


# @login_required
def portfolio(request):
    return render(request, 'portfolio.html')


@login_required
def settings(request):
    context = {
        "user": request.user,
        # "username": request.user.name
    }
    return render(request, 'settings.html', context)


def contactme_complete(request):
    return render(request, 'contactme_complete.html')


class ContactmeView(View):
    def get(self, request):
        return render(request, 'contactme.html')

    def post(self, request):
        subject = request.POST.get('subject', None)
        username = request.POST.get('username', None)
        sender = request.POST.get('email', None)
        text = request.POST.get('text', None)
        body = text + "\n by " + username + "(" + sender + ")"
        try:
            # print('######')
            email = EmailMessage(
                subject=str(subject), body=str(body), from_email=str(sender), to=[conf_settings.EMAIL_HOST_USER])
            email.send()
            # send_mail(subject=subject, message=text, from_email=sender,
            #           recipient_list=[conf_settings.EMAIL_HOST_USER])
        except BadHeaderError:
            return HttpResponse
        return redirect('accounts:contactme_complete')


def registration(request):
    return render(request, 'accounts/registration.html')


class RegistrationView(View):
    def get(self, request):
        return render(request, 'accounts/registration.html')

    def post(self, request):
        username = request.POST.get('username', None)
        email = request.POST.get('email', None)
        password = request.POST.get('password', None)
        repassword = request.POST.get('repassword', None)

        context = {
            'username': username,
            'email': email
        }
        if get_user_model().objects.filter(username=username).exists():
            messages.error(request, '既にこのアカウント名が存在します')
            return render(request, 'accounts/registration.html', context)

        if not get_user_model().objects.filter(email=email).exists():
            if len(password) < 7:
                messages.error(request, 'パスワードを７字以上にしてください')
                return render(request,  'accounts/registration.html', context)
            if password != repassword:
                messages.error(request, 'パスワードとパスワード確認は同じ値を入力してください')
                return render(request,  'accounts/registration.html', context)

            user = get_user_model().objects.create_user(
                username=username, email=email, password=password)
            current_site = get_current_site(request)
            uid = urlsafe_base64_encode(force_bytes(user.pk))
            token = account_activation_token.make_token(user)
            link = reverse('accounts:activate', kwargs={
                'uidb64': uid,
                'token': token
            })

            activate_url = 'http://' + current_site.domain + link
            email_body = user.email + \
                'さん、ご登録ありがとうございます。\nメールアドレスに間違いがなければ、以下のリンクからログインしてください。 \n' + activate_url
            data = {'email_body': email_body, 'to_email': user.email,
                    'email_subject': 'ユーザー登録を完了してください'}
            EmailUtil.send_email(data)
            messages.success(request, '確認メールを送信しました')
            return render(request, 'accounts/registration.html')

        messages.error(request, '既にアカウントが存在します')
        return render(request, 'accounts/registration.html', context)


class VerificationView(View):
    def get(self, request, uidb64, token):
        try:
            id = force_str(urlsafe_base64_decode(uidb64))
            user = get_user_model().objects.get(pk=id)

            if not account_activation_token.check_token(user, token):
                redirect('/login')

            if user.is_verified:
                return redirect('/login')

            user.is_verified = True
            user.save()
            Profile.objects.create(user=user, nick_name='ななしさん')

            messages.success(request, 'アカウント作成が完了しました')
            return redirect('/login')
        except Exception as e:
            # print(e)
            pass

        return redirect('/login')


class LoginView(View):
    def get(self, request):
        return render(request, 'accounts/login.html')

    def post(self, request):
        email = request.POST.get('email', None)
        password = request.POST.get('password', None)

        context = {
            'email': request.POST.get('email', None)
        }

        if password:
            user = authenticate(email=email, password=password)
            if user:
                if user.is_active:
                    login(request, user)
                    return redirect('/')
                messages.error(request, 'ユーザー登録が完了していません\nメールを確認してください')
                return render(request, 'accounts/login.html')

            messages.error(request, 'メールアドレスまたは、パスワードが間違っています')
            return render(request, 'accounts/login.html', context)
        messages.error(request, 'すべての項目を入力してください')
        return render(request, 'accounts/login.html', context)


class LogoutView(View):
    def get(self, request):
        logout(request)
        messages.success(request, 'ログアウトが完了しました')
        return redirect('/login')


class PasswordChangeView(LoginRequiredMixin, PasswordChangeView):
    success_url = reverse_lazy('accounts:password_change_done')
    template_name = 'accounts/password_change.html'

    # def get_context_data(self, **kwargs):
    #     context =  super().get_context_data(**kwargs)
    #     context['form_name'] = 'password_change'
    #     return context


class PasswordChangeDoneView(LoginRequiredMixin, PasswordChangeDoneView):
    template_name = 'accounts/password_change_done.html'


class PasswordResetView(PasswordResetView):
    """パスワード変更用URLの送付ページ"""
    subject_template_name = 'accounts/mail_template/password_reset/subject.txt'
    email_template_name = 'accounts/mail_template/password_reset/message.txt'
    template_name = 'accounts/password_reset_form.html'
    form_class = MyPasswordResetForm
    success_url = reverse_lazy('accounts:password_reset_done')


class PasswordResetDoneView(PasswordResetDoneView):
    """パスワード変更用URLを送りましたページ"""
    template_name = 'accounts/password_reset_done.html'


class PasswordResetConfirmView(PasswordResetConfirmView):
    """新パスワード入力ページ"""
    form_class = MySetPasswordForm
    success_url = reverse_lazy('accounts:password_reset_complete')
    template_name = 'accounts/password_reset_confirm.html'


class PasswordResetCompleteView(PasswordResetCompleteView):
    """新パスワード設定しましたページ"""
    template_name = 'accounts/password_reset_complete.html'


@login_required
def edit_account_username(request, user_id):
    if request.user.id == user_id:
        username = request.POST.get('username', None)
        user = get_user_model().objects.get(id=user.id).update(username=username)
    return redirect('/login')


class UsernameChangeView(LoginRequiredMixin, View):
    def get(self, request):
        return render(request, 'accounts/username_change.html')

    def post(self, request):
        username = request.POST.get('username', None)

        if username:
            if get_user_model().objects.filter(username=username).exists():
                messages.error(request, '既にこのアカウント名が存在します')
                return render(request, 'accounts/username_change.html')
            if len(username) > 20:
                messages.error(request, '20字以内で入力してください')
                return render(request, 'accounts/username_change.html')

            get_user_model().objects.filter(id=request.user.id).update(username=username)
            return redirect('/settings')

        messages.error(request, 'ユーザーネームを入力してください')
        return render(request, 'accounts/username_change.html')


@login_required
def delete_account(request, user_id):

    if request.user.id == user_id:
        try:
            user = get_user_model().objects.filter(id=user_id).first()
            user.delete()
            return redirect('/login')
        except:
            # return JsonResponse({'error': 'error'})
            return redirect('/settings')

    return redirect('/settings')


@login_required
def get_profile(request):
    profile = Profile.objects.get(user=request.user)
    favorite_posts = request.user.favorite_post.all()
    context = {
        'profile': profile,
        'favorite_posts': favorite_posts,
    }

templates/accounts/login.html
{% extends "base.html" %} {% load static %}
<!--  -->
{% block styles %}
<link rel="stylesheet" href="{% static 'accounts/css/login.css' %}" />
<link rel="stylesheet" href="{% static 'accounts/css/messages.css' %}" />
{% endblock %}
<!--  -->
{% block title %}ログイン{% endblock %}
<!--  -->
{% block content %}
<div class="card">
  <div class="title">ログイン</div>
        <!-- message -->

  <form action="{% url 'accounts:login' %}" method="post">
    {% csrf_token %}
    <div class="form_group">
      {% include 'components/messages.html' %}
      <span id="message"></span>

      <div class="email content">
        <!-- <i class="bx bx-envelope"></i> -->
        <input
          type="email"
          name="email"
          class="field"
          id="emailField"
          value="{{email}}"
          placeholder=" "
          required
        />
        <span>メールアドレス</span>
      </div>
      <div class="password content">
        <!-- <i class="bx bx-lock"></i> -->
        <input
          type="password"
          name="password"
          class="field"
          id="passwordField"
          placeholder=" "
          required
        />
        <span>パスワード</span>
      </div>
      <button type="submit" class="btn">ログイン</button>
      <div class="link">
        <a href="{% url 'accounts:password_reset' %}" class="to-reset">パスワードを忘れた方</a>
       </div>
       <hr>

      <div class="link">
        <a href="{% url 'accounts:registration' %}" class="to-reset">アカウント登録画面へ</a>
       </div>


    </div>
  </form>
</div>

{% endblock %}

templates/accounts/password_change.html
{% extends "base.html" %} {% load static %}
<!--  -->
{% block styles %}
<link rel="stylesheet" href="{% static 'accounts/css/password_change.css' %}" />
{% endblock %}
<!--  -->
{% block title %}パスワード変更{% endblock %}
<!--  -->
{% block content %}
<div class="card">
  <div class="title">パスワード変更</div>
  <form action="" method="POST">
    {% csrf_token %} {{ form.non_field_errors }} {% for field in form %}
    <div class="form-group">
      <label class="form-label" for="{{ field.id_for_label }}"
        >{{ field.label_tag }}</label
      >
      {{ field }} {{ field.errors }}
    </div>
    {% endfor %}

    <div class="form-group submit">
      <div class="button">
        <button type="submit" class="btn">変更</button>
      </div>

      <div class="button">
        <a href="{% url 'accounts:settings' %}" class="settings">戻る</a>
      </div>
    </div>
  </form>
</div>
{% endblock %}

templates/accounts/password_change_done.html
{% extends "base.html" %} {% load static %}
<!--  -->
{% block styles %}
<link
  rel="stylesheet"
  href="{% static 'accounts/css/password_change_done.css' %}"
/>
{% endblock %}
<!--  -->
{% block title %}パスワード変更完了{% endblock %}
<!--  -->
{% block content %}
<div class="card">
  <div class="col-4">
    <div class="title">パスワードを変更しました。</div>
    <div class="form-group">
      <div class="button">
        <a class="btn" href="{% url 'accounts:home' %}">ホームへ</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/accounts/password_reset_complete.html
{% extends "base.html" %} {% load static %}
<!--  -->
{% block styles %}
<link rel="stylesheet" href="{% static 'accounts/css/password_reset_complete.css' %}" />
{% endblock %}
<!--  -->
{% block title %}パスワードの再設定{% endblock %}
<!--  -->
{% block content %}
<div class="card">
<p>
    パスワード再設定を完了しました。
    <div class="button">
        <a class="btn" href="{% url 'accounts:login' %}">ログイン</a>
    </div>
</p>
</div>
{% endblock %}

templates/accounts/password_reset_form.html
{% extends "base.html" %} {% load static %}
<!--  -->
{% block styles %}
<link rel="stylesheet" href="{% static 'accounts/css/password_reset.css' %}" />
{% endblock %}
<!--  -->
{% block title %}パスワードの再設定{% endblock %}
<!--  -->
{% block content %}

<div class="card">
    <div class="title">パスワードを再設定する場合はメールアドレスを送信してください。</div>
    <form action="" method="POST">
        {% csrf_token %}

        {{ form.non_field_errors }}
        
        {% for field in form %}
        <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
            {{ field }}
            {{ field.errors }}
        </div>
        {% endfor %}
        
        <div class="button">
            <button type="submit" class="btn">送信</button>
        </div>
        <hr>
        <div class="login">
          <a href="{% url 'accounts:login' %}" class="to-login">ログイン画面へ</a>
         </div>
       </div>
    </form>
</div>

{% endblock %}

templates/accounts/profile.html
{% extends "base.html" %} {% load static %}
<!--  -->
{% block styles %}
<link rel="stylesheet" href="{% static 'accounts/css/profile.css' %}" />
{% endblock %}
<!--  -->
{% block title %}{{profile.nick_name}}{% endblock %}
<!--  -->
{% block content %}
<div class="profile">
  <div class="nickName">
    {{profile.nick_name}}
  </div>
  <div class="username">@{{profile.user.username}}</div>

  <div class="change-btns">
      <a class="change-btn" href="{% url 'accounts:profile_change' %}">プロフィールの変更</a>
  </div>
  <div class="navigation">
    <div class="favorite_post">
      <a href="{% url 'accounts:profile' %}" class="active_section">
        お気に入り
      </a>
    </div>
    <div class="comments">
      <a href="{% url 'accounts:profile_comments' %}">
        コメント
      </a>
    </div>
  </div>

  <div class="post-list">
    <div class="posts">
      {% for post in favorite_posts %}
      <ul>
        <li class="card">
          <div class="date">
            <div class="updated-at">
              {% if post.created_at|date:"Y-m-d" != post.updated_at|date:"Y-m-d" %}
                <i class='bx bx-revision'></i>
                {{post.updated_at|date:"Y-m-d"}}
              {% endif %}
            </div>
    
            <div class="created-at">
              <i class='bx bx-pencil'></i>
              {{post.created_at|date:"Y-m-d"}}
            </div>
          </div>
    
          <div class="title">
            <a href="{% url 'articles:article-detail' pk=post.id %}">
              {{post.title}}
            </a>
          </div>
    
          <a
            href="{% url 'articles:article-category' category=post.category %}"
            class="category"
          >
            <i class='bx bx-folder-open'></i>
            {{post.category}}
          </a>

          <div class="tag-list">
            {% for tag in post.tags.all %}
            <a href="{% url 'articles:article-tag' tag=tag.name %}" class="tag">
              <i class='bx bx-purchase-tag'></i>
              {{tag.name}}
            </a>
            {% endfor %}
          </div>
    
        </li>
      </ul>
      {% endfor %}
    </div>
  </div>
</div>

{% endblock %}

templates/accounts/profile_change.html
{% extends "base.html" %} {% load static %}
<!--  -->
{% block styles %}
<link rel="stylesheet" href="{% static 'accounts/css/profile_change.css' %}" />
<link rel="stylesheet" href="{% static 'accounts/css/messages.css' %}" />
{% endblock %}
<!--  -->
{% block title %}{{profile.nick_name}}{% endblock %}
<!--  -->
{% block content %}
<div class="card">
  <div class="title">ニックネームを変更</div>
  <!-- message -->

  <form action="{% url 'accounts:profile_change' %}" method="post">
    {% csrf_token %}
    <div class="form_group">
      {% include 'components/messages.html' %}
      <div class="nickName">
        <input
          type="text"
          name="nickName"
          placeholder="ニックネーム"
          class="field"
          id="nickNameField"
          value="{{nickName}}"
        />
      </div>

      <button type="submit" class="btn">変更</button>

      <a href="{% url 'accounts:profile' %}" class="to_prfile">戻る</a>
    </div>
  </form>
</div>
{% endblock %}

templates/accounts/profile_comments.html
{% extends "base.html" %} {% load static %}
<!--  -->
{% block styles %}
<link rel="stylesheet" href="{% static 'accounts/css/profile.css' %}" />
{% endblock %}
<!--  -->
{% block title %}{{profile.nick_name}}{% endblock %}
<!--  -->
{% block content %}
<div class="profile">
  <div class="nickName">{{profile.nick_name}}</div>
  <div class="username">@{{profile.user.username}}</div>
  <div class="change-btns">
    <a class="change-btn" href="{% url 'accounts:profile_change' %}"
      >プロフィールの変更</a
    >
    <!-- <a class="change-btn" href="{% url 'accounts:password_change' %}">パスワードの変更</a> -->
  </div>
  <div class="navigation">
    <div class="favorite_post">
      <a href="{% url 'accounts:profile' %}"> お気に入り </a>
    </div>
    <div class="comments">
      <a href="{% url 'accounts:profile_comments' %}" class="active_section">
        コメント
      </a>
    </div>
  </div>

  <div class="comment-list">
    <div class="comments">
      {% for comment in comments %}
      <ul>
        <li class="card">
          <div class="date">
            <div class="created-at">
              <i class="bx bx-pencil"></i>
              {{comment.created_at|date:"Y-m-d"}}
            </div>
          </div>

          <div class="comment">
            {{comment.comment}}
          </div>
          
          <div class="title">
            <a href="{% url 'articles:article-detail' pk=comment.post.id %}">
              記事：{{ comment.post.title }}
            </a>
          </div>

        </li>
      </ul>
      {% endfor %}
    </div>
  </div>
</div>

{% endblock %}

templates/accounts/registration.html
{% extends 'base.html' %}
<!--  -->
{% load static %}
<!--  -->
{% block styles %}
<link rel="stylesheet" href="{% static 'accounts/css/registration.css' %}" />
<link rel="stylesheet" href="{% static 'accounts/css/messages.css' %}" />
{% endblock %}
<!--  -->
{% block scripts %}
{% endblock %}
<!--  -->
{% block title %} {% endblock %}
<!--  -->
{% block content %}
<div class="card">
  <div class="title">アカウント登録</div>
  <form action="{% url 'accounts:registration' %}" method="post">
    {% csrf_token %}

    <div class="form_group">
      <!-- message -->
      {% include 'components/messages.html' %}
      <div class="username content">
        <!-- <i class="bx bx-envelope"></i> -->
        <input
          type="text"
          name="username"
          class="field"
          id="usernameField"
          value="{{username}}"
          placeholder=" "
          required
        />
        <span>ユーザーネーム</span>
      </div>

      <div class="email content">
        <!-- <i class="bx bx-envelope"></i> -->
        <input
          type="email"
          name="email"
          class="field"
          id="emailField"
          value="{{email}}"
          placeholder=" "
          required
        />
        <span>メールアドレス</span>
      </div>

      <div class="password content">
        <input
          type="password"
          name="password"
          class="field"
          id="passwordField"
          placeholder=" "
          required
        />
        <span>パスワード（7字以上）</span>
      </div>

      <div class="password content">
        <input
          type="password"
          name="repassword"
          class="field"
          id="repasswordField"
          placeholder=" "
          required
        />
        <span>パスワード確認</span>
      </div>

      <button type="submit" class="btn">登録</button>
      <hr />
      <div class="login">
        <a href="{% url 'accounts:login' %}" class="to-login">ログイン画面へ</a>
      </div>
    </div>
  </form>
</div>

{% endblock %}

templates/accounts/username_change.html
{% extends "base.html" %} {% load static %}
<!--  -->
{% block styles %}
<link rel="stylesheet" href="{% static 'accounts/css/profile_change.css' %}" />
<link rel="stylesheet" href="{% static 'accounts/css/messages.css' %}" />
{% endblock %}
<!--  -->
{% block title %}ユーザーネームを変更{% endblock %}
<!--  -->
{% block content %}
<div class="card">
  <div class="title">ユーザーネームを変更</div>
  <!-- message -->

  <form action="{% url 'accounts:username_change' %}" method="post">
    {% csrf_token %}
    <div class="form_group">
      {% include 'components/messages.html' %}
      <div class="nickName">
        <input
          type="text"
          name="username"
          placeholder="ニックネーム"
          class="field"
          id="usernameNameField"
          value="{{username}}"
        />
      </div>

      <button type="submit" class="btn">変更</button>

      <a href="{% url 'accounts:settings' %}" class="to_prfile">戻る</a>
    </div>
  </form>
</div>
{% endblock %}