articles/urls.py
from django.urls import path
from .views import (
    article_list,
    article_search,
    article_detail,
    like_unlike_article,
    article_tag,
    article_category,
    create_comment,
    delete_comment
)

app_name = 'articles'

urlpatterns = [
    path('', article_list, name='article-list'),
    path('search', article_search, name='article-search'),
    path('detail/<uuid:pk>', article_detail, name='article-detail'),
    path('detail/like/<uuid:pk>', like_unlike_article, name='like'),
    path('category/<str:category>', article_category, name='article-category'),
    path('tag/<str:tag>', article_tag, name='article-tag'),
    path('comment/<uuid:article_id>', create_comment, name='comment-create'),
    path('comment-delete/<uuid:comment_id>',
         delete_comment, name='comment-delete'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls', namespace='accounts')),
    path('articles/', include('articles.urls', namespace='articles')),
    re_path('markdownx/', include('markdownx.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

articles/models.py
import uuid
from django.db import models
from django.contrib.auth import get_user_model
from django.db.models.deletion import CASCADE, RestrictedError
from django.conf import settings
import os
from markdownx.models import MarkdownxField
from django.utils.safestring import mark_safe
from markdownx.utils import markdownify


class Category(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Tag(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


def upload_avatar_path(instance, filename):
    profile_avarar_path = 'post/post_{0}.jpg'.format(str(instance.id))
    full_path = os.path.join(settings.MEDIA_ROOT, profile_avarar_path)
    # '/'.join(['avatars', str(instance.id) + str(".") + str(ext)])
    # ext = filename.split('.')[-1]
    if os.path.exists(full_path):
        os.remove(full_path)
        # return profile_avarar_name_0
    # else:
    return profile_avarar_path


class Post(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField('タイトル', max_length=120)
    content = MarkdownxField('テキスト')
    overview = models.TextField('プレビュー', blank=True, null=True)
    category = models.ForeignKey(
        Category, blank=True, null=True, related_name='category_post', on_delete=CASCADE)
    tags = models.ManyToManyField(
        Tag, blank=True, related_name='post_tags')
    liked = models.ManyToManyField(
        get_user_model(), blank=True, related_name='favorite_post')
    created_at = models.DateTimeField('登録日時', auto_now_add=True)
    updated_at = models.DateTimeField('更新日時', auto_now=True)
    # img = models.ImageField(blank=True, null=True,
    #                         upload_to=upload_avatar_path)

    class Meta:
        ordering = ['-created_at', ]

    def __str__(self):
        return f"{self.title}-{self.category}"

    def get_text_markdownx(self):
        return mark_safe(markdownify(self.content))

    def get_preview_content(self):
        return self.overview[:200]


class Comment(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    comment = models.CharField(max_length=200)
    commented_by = models.ForeignKey(
        get_user_model(), related_name='user_comment',
        blank=True, null=True,
        on_delete=models.CASCADE
    )
    commented_at = models.DateTimeField('登録日時', auto_now_add=True)
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name='comment')
    created_at = models.DateTimeField('登録日時', auto_now_add=True)

    class Meta:
        ordering = ['-commented_at', ]

    def __str__(self):
        return self.comment

articles/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from .models import Category, Comment, Post, Tag


def article_list(request):
    posts = Post.objects.all()
    categories = Category.objects.all()
    tags = Tag.objects.all()

    paginator = Paginator(posts, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'title': "記事一覧",
        # 'posts': posts,
        'page_obj': page_obj,
        'categories': categories,
        'tags': tags
    }
    return render(request, 'articles/articlelist.html', context)


def article_search(request):
    q = str(request.GET.get('q'))
    # print(word)
    posts = Post.objects.filter(title__icontains=q)
    categories = Category.objects.all()
    tags = Tag.objects.all()
    paginator = Paginator(posts, 10)
    page_number = request.GET.get('page')
    # print(q)
    print(page_number)
    page_obj = paginator.get_page(page_number)

    context = {
        'title': f'検索結果：{q}',
        'page_obj': page_obj,
        'categories': categories,
        'tags': tags,
        'q': q
    }
    return render(request, 'articles/articlelist.html', context)


def article_category(request, category):
    posts = Post.objects.filter(category__name=category)
    categories = Category.objects.all()
    tags = Tag.objects.all()
    paginator = Paginator(posts, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'title': f'カテゴリ：{category}',
        'page_obj': page_obj,
        'categories': categories,
        'tags': tags
    }
    return render(request, 'articles/articlelist.html', context)


def article_tag(request, tag):
    posts = Post.objects.filter(tags__name=tag)
    categories = Category.objects.all()
    tags = Tag.objects.all()
    paginator = Paginator(posts, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'title': f'タグ：{tag}',
        'page_obj': page_obj,
        'categories': categories,
        'tags': tags,
    }
    return render(request, 'articles/articlelist.html', context)


def article_detail(request, pk):
    post = get_object_or_404(Post, id=pk)
    user_id = request.user.id
    is_liked = str(user_id) in [str(i.id) for i in post.liked.all()]

    # print([str(i.id) for i in study.liked.all()])
    context = {
        'post': post,
        'is_liked': is_liked
    }
    # print(study.content)
    return render(request, 'articles/articledetail.html', context)


@login_required
def like_unlike_article(request, pk):
    # いいねをするもしくは外すUser
    user = request.user
    try:
        # いいねされるまたは外される学習項目
        to_like = Post.objects.get(id=pk)

        if user in to_like.liked.all():
            to_like.liked.remove(user)
            to_like.save()

            return JsonResponse({'data': 'unlike'})
        else:
            to_like.liked.add(user)
            to_like.save()
            return JsonResponse({'data': 'like'})
    except Exception as e:
        # print(e)
        pass


@login_required
def create_comment(request, article_id):
    if request.method == "POST":
        text = request.POST.get('comment', None)
        post = Post.objects.filter(id=article_id).first()

        Comment.objects.create(
            comment=text, commented_by=request.user, post=post)
        return redirect('articles:article-detail', article_id)


@login_required
def delete_comment(request, comment_id):
    if request.method == "POST":
        data = get_object_or_404(Comment, id=comment_id)
        data.delete()
        article_id = str(data.post.id)
        return redirect('articles:article-detail', article_id)

templates/articles/articledetail.html
{% extends "base.html" %} {% load static %}
<!-- css -->
{% block styles %}
<link rel="stylesheet" href="{% static 'articles/css/articleDetail.css' %}" />
<link rel="stylesheet" href="{% static 'articles/css/commentForm.css' %}" />
<link rel="stylesheet" href="{% static 'articles/css/markdown.css' %}" />
<link
  rel="stylesheet"
  href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/11.5.1/styles/monokai.min.css"
/>
{% endblock %}
<!-- js -->
{% block scripts %}
<script src="{% static 'articles/js/articleDetail.js' %}" defer></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/11.5.1/highlight.min.js"></script>
<script>
  hljs.highlightAll();
</script>
{% endblock scripts %}
<!-- title -->
{% block title %} {{post.title}} {% endblock %}
<!-- html -->
{% block content %}

<div class="article">
  <form class="good-button" id="good-button">
    {% csrf_token %} {% if is_liked %}

    <i class="bx bxs-heart like" id="like" data-postid="{{post.id}}"></i>
    {% else %}
    <i class="bx bx-heart like" id="like" data-postid="{{post.id}}"></i>
    {% endif %}
  </form>
  <div class="comment-button">
    <a href="#comment">
      <i class="bx bx-comment-detail"></i>
    </a>
  </div>

  <div class="category">
    <a
      href="{% url 'articles:article-category' category=post.category %}"
      class="category"
    >
      <i class="bx bx-folder-open"></i>
      {{ post.category}}
    </a>
  </div>
  <div class="article-title">{{ post.title }}</div>

  <div class="date">
    <div class="updated-at">
      {% if post.created_at|date:"Y-m-d" != post.updated_at|date:"Y-m-d" %}
      <i class="bx bx-revision"></i>
      {{ post.updated_at|date:"Y-m-d" }} {% endif %}
    </div>

    <div class="created-at">
      <i class="bx bx-pencil"></i>
      {{ post.created_at|date:"Y-m-d" }}
    </div>
  </div>


  <div class="tags">
    {% if post.tags.all != None %} {% for tag in post.tags.all %}
    <a href="{% url 'articles:article-tag' tag=tag.name %}" class="tag">
      <i class="bx bx-purchase-tag"></i>
      {{tag.name}}
    </a>
    {% endfor %} {% endif %}
  </div>

  <div class="markdown">{{ post.get_text_markdownx | safe }}</div>

  <div class="comment_container"  id="comment">
    <!-- <div>Comment</div> -->
    <div class="comment_title">
      <i class='bx bxs-right-arrow'></i>
      コメント
    </div>

    <form action="{% url 'articles:comment-create' post.id %}" method="post" class="comment_form">
      {% csrf_token %}
      <div class="comment_form__input__content">
        <textarea
          type="text"
          name="comment"
          rows="5"
          cols="45"
          minlength="1"
          maxlength="250"
          required
          id="commentField"
          value="{{comment}}"
        ></textarea>
        <span>コメント(250文字以内)</span>
      </div>
      <p>※コメントするにはログインが必要です。</p>

      <div class="comment_button_style">
        <button type="submit" class="comment_button">送信</button>
      </div>
    </form>

    <div class="comment-list">

      <div class="comments">
        {% for comment in post.comment.all %}
        <ul>
          <li class="card">
            <div class="date">
              <div class="created-at">
                <i class="bx bx-pencil"></i>
                {{comment.created_at|date:"Y-m-d"}}
              </div>
            </div>
            <div>
              {{comment.commented_by.profile.nick_name}}
              @{{comment.commented_by.username}}
            </div>
  
            <div class="comment">
              {{comment.comment}}
            </div>

            {% if comment.commented_by.id == request.user.id %}
            <!-- <div class="delete-buttton" > -->
              <form action="{% url 'articles:comment-delete' comment.id %}" method="post" class="delete-buttton" id="delete-button">
              {% csrf_token %}
                <button type="submit" class="btn">
                  <i class='bx bxs-trash-alt'></i>
                </button>
              </form>
            <!-- </div> -->
            {% endif %}

          </li>
        </ul>
        {% endfor %}
      </div>
    </div>
  </div>

  <!-- <a href="{% url 'articles:article-list' %}" class="back-to-list">一覧へ</a> -->
</div>

{% endblock %}

templates/articles/articlelist.html
{% extends "base.html" %} {% load static %}
<!-- css -->
{% block styles %}
<link rel="stylesheet" href="{% static 'articles/css/articleList.css' %}" />
{% endblock %}
<!-- js -->
{% block scripts %}
{% endblock scripts %}
<!-- title -->
{% block title %} {{title}} {% endblock %}
<!-- html -->
{% block content %}
<div class="post-list">
  <div class="post-list-title">{{ title }}</div>
  <!-- <hr /> -->

  <div class="content">
    <div class="posts">
      {% for post in page_obj %}
      <ul>
        <li class="card">
          <!-- <div class="date"> -->
          <a class="date" href="{% url 'articles:article-detail' pk=post.id %}">
          
            <div class="updated-at">
              {% if post.created_at|date:"Y-m-d" != post.updated_at|date:"Y-m-d" %}
              <i class="bx bx-revision"></i>
              {{post.updated_at|date:"Y-m-d"}} {% endif %}
            </div>

            <div class="created-at">
              <i class="bx bx-pencil"></i>
              {{post.created_at|date:"Y-m-d"}}
            </div>
          </a>
          <!-- </div> -->

          <div class="title">
            <a href="{% url 'articles:article-detail' pk=post.id %}">
              {{post.title}}
            </a>
          </div>



          <div class="tag-list">
            <a
              href="{% url 'articles:article-category' category=post.category %}"
              class="category"
            >
              <i class="bx bx-folder-open"></i>
              {{post.category}}
            </a>
            {% for tag in post.tags.all %}
            <a href="{% url 'articles:article-tag' tag=tag.name %}" class="tag">
              <i class="bx bx-purchase-tag"></i>
              {{tag.name}}
            </a>
            {% endfor %}
          </div>
        </li>
      </ul>
      {% endfor %}

      {% if not page_obj. is None %}
        {% if q %}
          <div class="pagination">
            <span class="step-links">
              {% if page_obj.has_previous %}
                <li class="chevrons">
                  <a href="?q={{ q }}&page=1">
                    <!-- <i class='bx bx-chevrons-left'></i> -->
                    <i class='bx bxs-chevrons-left'></i>
                  </a>
                </li>
                  <!-- <a href="?q={{ q }}&page={{ page_obj.previous_page_number }}">previous</a> -->
              {% endif %}
      
              {% for i in page_obj.paginator.page_range %}
                {% if page_obj.number == i %}
                  <li class="active"><span>{{ i }}</span></li>
    
                {% else %}
                  <li><a href="?q={{ q }}&page={{ i }}">{{ i }}</a></li>
                {% endif %}
              {% endfor %}

              {% if page_obj.has_next %}
                  <!-- <a href="?q={{ q }}&page={{ page_obj.next_page_number }}">next</a> -->
                  <li class="chevrons">
                    <a href="?q={{ q }}&page={{ page_obj.paginator.num_pages }}">
                      <!-- <i class='bx bx-chevrons-right'></i> -->
                      <i class='bx bxs-chevrons-right'></i>
                    </a>
                  </li>
              {% endif %}
            </span>
          </div>
        {% else %}
          <div class="pagination">
            <span class="step-links">
              {% if page_obj.has_previous %}
                <li class="chevrons">
                  <a href="?page=1">
                    <!-- <i class='bx bx-chevrons-left'></i> -->
                    <i class='bx bxs-chevrons-left'></i>
                  </a>
                </li>
                  <!-- <a href="?q={{ q }}&page={{ page_obj.previous_page_number }}">previous</a> -->
              {% endif %}
      
              {% for i in page_obj.paginator.page_range %}
                {% if page_obj.number == i %}
                  <li class="active"><span>{{ i }}</span></li>

                {% else %}
                  <li><a href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
              {% endfor %}

              {% if page_obj.has_next %}
                  <!-- <a href="?q={{ q }}&page={{ page_obj.next_page_number }}">next</a> -->
                  <li class="chevrons">
                    <a href="?page={{ page_obj.paginator.num_pages }}">
                      <!-- <i class='bx bx-chevrons-right'></i> -->
                      <i class='bx bxs-chevrons-right'></i>
                    </a>
                  </li>
              {% endif %}
            </span>
          </div>
        {% endif %}
      {% endif %}

    </div>

    <div class="categories-tags">
      <div class="categories-title">カテゴリー</div>

      {% for category in categories %}
      <div class="category-tag">
        <a
          href="{% url 'articles:article-category' category=category %}"
          class="category-link"
        >
          <!-- <i class="bx bx-category"></i> -->
          <i class="bx bx-folder-open"></i>
          {{category.name}}
        </a>
      </div>
      {% endfor %}

      <div class="categories-title">タグ</div>
      {% for tag in tags %}
      <div class="category-tag">
        <a href="{% url 'articles:article-tag' tag=tag %}" class="tag-link">
          <i class="bx bx-purchase-tag"></i>
          {{tag.name}}
        </a>
      </div>
      {% endfor %}
    </div>
  </div>
</div>

{% endblock %}