accounts/urls.py
from django.urls import path
from .views import (
    get_profile_comments,
    index,
    portfolio,
    settings,
    contactme_complete,
    ContactmeView,
    RegistrationView,
    LoginView,
    LogoutView,
    VerificationView,
    PasswordChangeView,
    PasswordChangeDoneView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
    UsernameChangeView,
    delete_account,
    get_profile,
    ProfileChangeView,
)

app_name = 'accounts'

urlpatterns = [
    path('', index, name='home'),
    path('portfolio', portfolio, name='portfolio'),
    path('settings', settings, name='settings'),
    path('contactme', ContactmeView.as_view(), name='contactme'),
    path('contactme/complete', contactme_complete, name='contactme_complete'),
    path('registration/', RegistrationView.as_view(),
         name='registration'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('activate/<uidb64>/<token>/',
         VerificationView.as_view(), name='activate'),
    # change password
    path('password-change/', PasswordChangeView.as_view(), name='password_change'),
    path('password-change/done', PasswordChangeDoneView.as_view(),
         name='password_change_done'),
    # reset password
    path('password_reset/', PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('password_reset/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/complete/', PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
    path('username_change', UsernameChangeView.as_view(), name='username_change'),
    path('acccount_delete/<uuid:user_id>',
         delete_account, name='acccount_delete'),
    # profile
    path('profile', get_profile, name='profile'),
    path('profile-comments', get_profile_comments, name='profile_comments'),
    path('profile-change', ProfileChangeView.as_view(), name='profile_change')
]

articles/urls.py
from django.urls import path
from .views import (
    article_list,
    article_search,
    article_detail,
    like_unlike_article,
    article_tag,
    article_category,
    create_comment,
    delete_comment
)

app_name = 'articles'

urlpatterns = [
    path('', article_list, name='article-list'),
    path('search', article_search, name='article-search'),
    path('detail/<uuid:pk>', article_detail, name='article-detail'),
    path('detail/like/<uuid:pk>', like_unlike_article, name='like'),
    path('category/<str:category>', article_category, name='article-category'),
    path('tag/<str:tag>', article_tag, name='article-tag'),
    path('comment/<uuid:article_id>', create_comment, name='comment-create'),
    path('comment-delete/<uuid:comment_id>',
         delete_comment, name='comment-delete'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls', namespace='accounts')),
    path('articles/', include('articles.urls', namespace='articles')),
    re_path('markdownx/', include('markdownx.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://unpkg.com/boxicons@2.1.2/css/boxicons.min.css"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="{% static 'css/globals.css' %}" />
    <link rel="stylesheet" href="{% static 'css/menubar.css' %}" />
    <link rel="stylesheet" href="{% static 'css/topbar.css' %}" />
    <link rel="stylesheet" href="{% static 'css/footer.css' %}" />

    {% block styles %} {% endblock %}
    <script src="{% static 'js/menubar.js' %}" defer></script>
    <script src="{% static 'js/topbar.js' %}" defer></script>
    {% block scripts %} {% endblock %}

    <title>ShiroLog | {% block title %}{% endblock %}</title>
  </head>

  <body>
    {% include 'topbar.html' %}

    <div class="container">{% block content %} {% endblock %}</div>

    {% include 'menubar.html' %}
    {% include 'footer.html' %}

  </body>
</html>

templates/contactme.html
{% extends "base.html" %} {% load static %}
<!-- css -->
{% block styles %}
<link rel="stylesheet" href="{% static 'css/contactme.css' %}" />
{% endblock %}
<!-- js -->
{% block scripts %}
{% endblock scripts %}
<!-- title -->
{% block title %} {{title}} {% endblock %}
<!-- html -->
{% block content %}
<div class="card">
  <div class="title">お問い合わせ</div>
  <!-- message -->

  <form action="{% url 'accounts:contactme' %}" method="post">
    {% csrf_token %}
    <div class="form_group">
      {% include 'components/messages.html' %}
      <span id="message"></span>

      <div class="username content">
        <input
          type="text"
          name="username"
          class="field"
          id="usernameField"
          value="{{username}}"
          placeholder=" "
          required
        />
        <span>名前</span>
      </div>
      <div class="email content">
        <input
          type="email"
          name="email"
          class="field"
          id="emailField"
          value="{{email}}"
          placeholder=" "
          required
        />
        <span>メールアドレス</span>
      </div>
      <div class="content">
        <input
          type="text"
          name="subject"
          class="field"
          id="subjectField"
          value="{{subject}}"
          placeholder=" "
          required
        />
        <span>件名</span>
      </div>

      <div class="content">
        <textarea
          class="field"
          name="text"
          rows="5"
          cols="45"
          minlength="1"
          maxlength="1000"
          id="textField"
          value="{{text}}"
          placeholder=" "
          required
        ></textarea>
        <span>テキスト(100文字以内)</span>
      </div>

      <button type="submit" class="btn">送信</button>
    </div>
  </form>
</div>

{% endblock %}

templates/contactme_complete.html
{% extends "base.html" %} {% load static %}
<!-- css -->
{% block styles %}
<link rel="stylesheet" href="{% static 'css/contactme.css' %}" />
{% endblock %}
<!-- js -->
{% block scripts %}
{% endblock scripts %}
<!-- title -->
{% block title %} {{title}} {% endblock %}
<!-- html -->
{% block content %}
<div class="card">
    <div class="title">送信を完了しました。</div>
</div>
{% endblock %}

templates/footer.html
<footer class="footer">
    <a href="/">
      <div
        class="logo"
      >
        &copy; 2022 Shirolog. All rights reserved.
      </div>
    </a>
  </footer>

templates/home.html
{% extends "base.html" %} {% load static %}
<!--  -->
{% block styles %}
<link rel="stylesheet" href="{% static 'css/home.css' %}" />
{% endblock %}
<!--  -->
{% block title %}ホーム{% endblock %}
<!--  -->
{% block content %}
<div class="content">
  {% for category in categories %}
    <div class="card">
      <div class="category_name">{{ category.name }}</div>
      {% for post in category.category_post.all|slice:":5" %}
      
       <div class="post_title">
        <a href="{% url 'articles:article-detail' pk=post.id %}">
          <i class='bx bx-right-arrow'></i>
          {{ post.title }}
        </a>
      </div>
      {% endfor %}

    
    <a
      href="{% url 'articles:article-category' category=category %}"
      class="category"
    >
      他の記事を読む
    </a>


    </div>
  {% endfor %}
</div>

{% endblock %}

templates/menubar.html
<div class="nav__menu" id="nav-menu">
  <ul class="nav__list">
    <li class="nav__item">
      <a href="{% url 'accounts:home' %}" class="nav__link active-link">
        <i class="bx bx-home-alt nav__icon"></i>
        <span class="nav__name">ホーム</span>
      </a>
    </li>

    <li class="nav__item">
      <a href="{% url 'accounts:profile' %}" class="nav__link">
        <i class="bx bx-user nav__icon"></i>
        <span class="nav__name">プロフィール</span>
      </a>
    </li>

    <li class="nav__item">
      <a href="{% url 'articles:article-list' %}" class="nav__link">
        <!-- <i class='bx bx-book-alt nav__icon'></i> -->
        <i class="bx bx-news nav__icon"></i>
        <span class="nav__name">記事</span>
      </a>
    </li>

    <li class="nav__item">
      <a href="{% url 'accounts:portfolio' %}" class="nav__link">
        <i class="bx bx-briefcase-alt nav__icon"></i>
        <span class="nav__name">ポートフォリオ</span>
      </a>
    </li>

    <li class="nav__item">
      <a href="{% url 'accounts:contactme' %}" class="nav__link">
        <!-- <i class='bx bx-message-square-detail nav__icon'></i> -->
        <i class="bx bx-mail-send nav__icon"></i>
        <span class="nav__name">お問い合わせ</span>
      </a>
    </li>
  </ul>

  {% if request.user.is_authenticated %}
  <ul class="nav__list nav_auth">
    <li class="nav__item">
      <a href="{% url 'accounts:settings' %}" class="nav__link">
        <i class="bx bx-cog nav__icon"></i>
        <span class="nav__name">設定</span>
      </a>
    </li>
    <li class="nav__item">
      <a href="{% url 'accounts:logout' %}" class="nav__link">
        <i class="bx bx-log-out nav__icon"></i>
        <span class="nav__name">ログアウト</span>
      </a>
    </li>
  </ul>
  {% else %}
  <ul class="nav__list nav_auth">
    <li class="nav__item">
      <a href="{% url 'accounts:login' %}" class="nav__link">
        <i class="bx bx-log-in nav__icon"></i>
        <span class="nav__name">ログイン</span>
      </a>
    </li>

    <li class="nav__item">
      <a href="{% url 'accounts:registration' %}" class="nav__link">
        <i class="bx bx-user-plus nav__icon"></i>
        <span class="nav__name">ユーザー登録</span>
      </a>
    </li>
  </ul>
  {% endif %}
</div>

templates/portfolio.html
{% extends "base.html" %} {% load static %}
<!-- css -->
{% block styles %}
<link rel="stylesheet" href="{% static 'css/portfolio.css' %}" />
{% endblock %}
<!-- js -->
{% block scripts %}
{% endblock scripts %}
<!-- title -->
{% block title %} ポートフォリオ {% endblock %}
<!-- html -->
{% block content %}
<div class="card">
  <div class="title">ポートフォリオ</div>
  <div class="text">Comming soon ...</div>
</div>
{% endblock %}

templates/settings.html
{% extends "base.html" %} {% load static %}
<!--  -->
{% block styles %}
<link rel="stylesheet" href="{% static 'accounts/css/settings.css' %}" />
<link rel="stylesheet" href="{% static 'accounts/css/messages.css' %}" />
{% endblock %}
<!--  -->
{% block scripts %}
<script src="{% static 'accounts/js/settings.js' %}" defer></script>
{% endblock scripts %}
{% block title %}設定{% endblock %}
<!--  -->
{% block content %}
<div class="settings">
    <div class="settings_title">設定</div>
    <br />
    
    <i class='bx bxs-right-arrow'></i>アカウント名の変更
    <div
        class="delete_account_button"
    >
        <a class="change-btn" href="{% url 'accounts:username_change' %}">
            アカウント名の変更する
        </a>
    </div>
    <br />
    <br />

    <i class='bx bxs-right-arrow'></i>パスワードの変更
    <div
        class="delete_account_button"
    >
        <a class="change-btn" href="{% url 'accounts:password_change' %}">パスワードの変更</a>
    </div>
    <br />
    <br />

    <i class='bx bxs-right-arrow'></i>アカウント削除
    <div
        class="delete_account_button open-modal"
    >
        アカウントを削除する
    </div>


</div>
<div class='modal'>
    <div class='overlay close-modal'></div>
    <div class='modal-content'>
      <div class='modal-text'>
        <h1>確認</h1>
        <p>{{user.username}}さん、本当にアカウントを削除しますか？</p>
        <p>データは全て削除されます。</p>            
        <div class='button' id="button">
        
            <div class='close-modal no'>
                いいえ 
            </div>

            <form action="{% url 'accounts:acccount_delete' user.id %}" method="post" class='yes'>
                {% csrf_token %}
                <button type="submit" class="btn">はい</button>
            </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/topbar.html
<header class="header">
  <div class="nav">
    <div class="logo">ShiroLog</div>

    <div class="icons" id="icons">
      <div class="icon menuBtn" id="menuBtn">
        <span class="border"></span>
        <span class="border"></span>
        <span class="border"></span>
      </div>
    </div>

    <div class="search">
      <form
        action="{% url 'articles:article-search' %}"
        class="search__form"
        method="get"
      >
        <input
          type="text"
          placeholder="キーワード検索"
          class="search__form__input"
          name="q"
          value="{{ request.GET.q }}"
          required
        />
        <button class="button">
          <i class="bx bx-search"></i>
        </button>
      </form>
    </div>
  </div>

  <div class="menubar" id="activeMenubar">
    <div class="menuTitle">Menu</div>
    <ul class="links">
      <li class="search">
        <!-- <div class="search"> -->
          <form
            action="{% url 'articles:article-search' %}"
            class="search__form"
            method="get"
          >
            <input
              type="text"
              placeholder="キーワード検索"
              class="search__form__input"
              name="q"
              value="{{ request.GET.q }}"
              required
            />
            <button class="button">
              <i class="bx bx-search"></i>
            </button>
          </form>
        <!-- </div> -->
      </li>

      {% if request.user.is_authenticated %}
      <li class="">
        <a href="{% url 'accounts:settings' %}" class="link">
          <!-- <i class='bx bx-cog nav__icon'></i> -->
          設定
        </a>
      </li>
      <li class="">
        <!-- <a href="/"> -->
        <a href="{% url 'accounts:logout' %}" class="link">
          <!-- <i class="bx bx-log-out nav__icon"></i> -->
          ログアウト
        </a>
      </li>
      {% else %}
      <li class="">
        <a href="{% url 'accounts:login' %}" class="link">
          <!-- <i class='bx bx-log-in nav__icon'></i> -->
          ログイン
        </a>
      </li>

      <li class="">
        <a href="{% url 'accounts:registration' %}" class="link">
          <!-- <i class='bx bx-user-plus nav__icon'></i> -->
          ユーザー登録
        </a>
      </li>
      {% endif %}
    </ul>
  </div>
</header>